
name: IST_DL21_Env
dependencies:
  - python=3.8
  - numpy Y
  - pillow Y
  - scikit-learn Y
  - pytorch Y
  - torchvision
  - torchtext 
  - huggingface::transformers
  - notebook
  - nb_conda_kernels
  - matplotlib
  - pip
  - pandas
  - pip:
    - timm
